name: Terraform Deploy to Azure

on: 
  push:
    branches:
      - master
      
jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "0.15.5"

      - name: Install Azure Cli 
        run: |
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
          Start-Process msiexec.exe -Wait -AgumentList '/quite'

      - name: Check Azure CLI version 
        run: az --version

      - name: Login via Azure CLI
        run: |
          az login --service-principal -u $env:AZURE_CLIENT_ID -P $ENV:AZURE_CLIENT_SECRET --tenant $env:AZURE_TENANT_ID
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION}}
        
      - name: Show Azure 
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Clean up Terraform files
        run: |
          #  Remove .terraform directory if it exist
          if (Test-Path ".terraform") {
              Remove-Item -Force .\tfplan
          }
          # continue-on-error: true  Continue with the workflow evenif cleanup fails
